### PR TITLE
Create publiccode.yml

### PR DESCRIPTION
**Pull request by libremente**
Hi @catalry @clam2310,
this PR:
* adds the `publiccode.yml` file which is needed in order to index this software in the Italian National catalog of FOSS software.

More information regarding this file are present [here](https://docs.italia.it/italia/developers-italia/gl-acquisition-and-reuse-software-for-pa-docs/en/stabile/index.html) and [here](https://docs.italia.it/italia/developers-italia/publiccodeyml-en/en/master/index.html)

It would be great to have this software listed in the [Developers Italia catalog](https://developers.italia.it/en/software). 

Please feel free to change the contents of the file as well.

Let me know if you need further details, thanks!

### CODE REVIEW

**Comment by catalry** [comment]
Dear @libremente , 
Thank you for your great contribution.
Please give us some time, your request in under validation from our side.
Will let you know ASAP

**Comment by libremente** [comment]
Hi @catalry, this is great news!
Let me know whether you need further support :+1:

**Comment by libremente** [comment]
Hi @catalry @clam2310 do you have any further news? We'd like to add EU-Survey to the Italian catalog since more and more administrations are starting to use it! Let me know how to proceed, thanks a lot :)

**Comment by libremente** [comment]
Hi @catalry @clam2310, any update on this one? Thanks!

**Comment by clam2310** [comment]
We added the file to the master branch

**Pull request closed without merging**
